version: "2.0"
services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/logs/:/var/logs/nginx/
    volumes_from:
      - htdocs
    ports:
      - "9091:80"
    links:
      - phpfpm
  phpfpm:
    image: yelfive/phpfpm:lv1-1.0
    volumes:
      - ./docker/phpfpm/php.ini:/usr/local/etc/php/php.ini:ro
    volumes_from:
      - htdocs
    links:
      - mariadb
  htdocs:
    image: busybox
    stdin_open: true
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
      - ./app:/var/www/html
  mariadb:
    image: mariadb
    volumes:
      - /etc/localtime:/etc/localtime
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mariadb/data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root4zentao
