version: "2.0"
services:
  nginx:
    build: docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/logs/:/opt/log/nginx/
    volumes_from:
      - htdocs
    ports:
      - "9090:80"
    links:
      - phpfpm
  phpfpm:
    build: docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    volumes_from:
      - htdocs
    links:
      - mysql
  htdocs:
    image: busybox
    stdin_open: true
    privileged: true
    volumes:
      - ./zentao:/var/www/html
  mysql:
    build: docker/mysql
    volumes:
        - ./docker/mysql/master.d:/etc/mysql/conf.d:ro
        - ./docker/mysql/data:/var/lib/mysql:rw
    env_file:
        - ./docker/mysql/.env
